### ISSUE TITLE
On Screen Calls IOS 

### ISSUE THREAD

**Issue by matrixbot** [element-hq/sygnal#332]
*This issue was originally created by [**@AnassDriate**](https://github.com/AnassDriate) at <https://github.com/matrix-org/sygnal/issues/332>.*

Hello,

This issue was traited many years ago, BUT The solution that was proposed is NOT working out of the box (at least for me)

1 . I created the VOIP pem and added it to sygnal 
my sygnal conf looks like : 

```
  lu.bundle.id:
    type: apns
    keyfile: /etc/sygnal/AuthKey.p8
    key_id: keyid
    team_id: 1F1F1F1F1F1
    topic: lu.mychat
    push_type: alert

 lu.bundle.id.voip:
    type: apns
    certfile: /etc/sygnal/voipem.pem
    topic:  lu.bundle.id
    push_type: voip
```
    
Additional information in the BuildSettings.swift 

```
static var pushKitAppIdProd: String {
        return baseBundleIdentifier + ".ios.voip.prod"
    }
    
    static var pushKitAppIdDev: String {
        return baseBundleIdentifier + ".ios.voip.dev"
    }
    
    static var pusherAppIdProd: String {
        return baseBundleIdentifier + ".ios.prod"
    }
    
    static var pusherAppIdDev: String {
        return baseBundleIdentifier + ".ios.dev"
    }
```

It would be intersting to know if i am missing something.

Regards,
