### ISSUE TITLE
Example config is missing "platform"

### ISSUE THREAD

**Issue by matrixbot** [element-hq/sygnal#80]
*This issue was originally created by [**@awesome-manuel**](https://github.com/awesome-manuel) at <https://github.com/matrix-org/sygnal/issues/80>.*

The key "platform" seems to be required for `apns`.
Somehow I don't even get an error if it is missing, sygnal is just not starting up.

**Comment by matrixbot** [comment]
*This comment was originally posted by [**@reivilibre**](https://github.com/reivilibre) at <https://github.com/matrix-org/sygnal/issues/80#issuecomment-651720336>.*


You're right that it could do with documenting (oups...)

BUT it won't prevent startup (both code and experience agree here...).

Could you share a bit more about your config (removing secrets), and your log?

**Comment by matrixbot** [comment]
*This comment was originally posted by [**@awesome-manuel**](https://github.com/awesome-manuel) at <https://github.com/matrix-org/sygnal/issues/80#issuecomment-654919897>.*


```yaml
log:
  setup:
    version: 1
    formatters:
      normal:
        format: "%(asctime)s [%(process)d] %(levelname)-5s %(name)s %(message)s"
    handlers:
      stdout:
        class: "logging.StreamHandler"
        formatter: "normal"
        stream: "ext://sys.stdout"
    root:
      handlers: ["stdout"]
      level: "INFO"
  access:
    x_forwarded_for: true

http:
  bind_addresses: ['0.0.0.0']
  port: 5000

apps:
  <id>:
    type: apns
    platform: prod
    certfile: mycert.pem
```

Getting a log file is a bit more complicated, cause we obviously don't run it anymore without the `platform` option.
