### ISSUE TITLE
VOIP: config for ios

### ISSUE THREAD

**Issue by matrixbot** [element-hq/sygnal#82]
*This issue was originally created by [**@Udit-DS**](https://github.com/Udit-DS) at <https://github.com/matrix-org/sygnal/issues/82>.*

I have following config in `sygnal.yaml` file for ios voip notifications

```
com.app.voip:
    type: apns
    certfile: certfile.pem
    platform: sandbox
    event_handlers:
      'm.call.invite': voip
```

but every time the `rejected` response and sometimes even BadDeviceToken(in logs) response

is there something I am missing?
